create table puntos (
   valor int not null check ( valor > 0 )
);

create table miembro (
   id_miembro   number
      generated by default on null as identity,
   tipo_miembro varchar2(10) not null check ( tipo_miembro in ( 'PROFESOR',
                                                                'ESTUDIANTE',
                                                                'EMPLEADO' ) ),
   genero       char(1) not null check ( genero in ( 'F',
                                               'M' ) ),
   nombre       varchar2(255) not null,
   
   -- Agregado ya que es necesario poder almacenar y modificar la cantidad total de puntos
   totalpuntos  number not null check ( totalpuntos >= 0 ),
   --

   primary key ( id_miembro )
);

create table miembroxcorreo (
   correo     varchar2(255) not null check ( correo like '%_@_%_.__%' ),
   id_miembro number not null,
   primary key ( correo ),
   foreign key ( id_miembro )
      references miembro ( id_miembro )
);

create table edificio (
   nombre varchar2(255) not null,
   primary key ( nombre )
);

create table piso (
   id_piso         number
      generated by default on null as identity,
   nombre_edificio varchar2(255) not null,
   primary key ( id_piso ),
   foreign key ( nombre_edificio )
      references edificio ( nombre )
         on delete set null
);

create table cafeteria (
   nombre  varchar2(255) not null,
   id_piso number not null,
   primary key ( nombre ),
   foreign key ( id_piso )
      references piso ( id_piso )
         on delete set null
);

create table producto (
   nombre_producto   varchar2(255) not null,
   precio            number not null check ( precio >= 0 ),
   nivel_reorden     number not null,
   cantidad_reoreden number not null,
   primary key ( nombre_producto )
);

create table colaborador (
   id_colaborador      number
      generated by default on null as identity,
   nombre              varchar2(255) not null,
   tipo_contrato       varchar2(50) not null check ( tipo_contrato in ( 'TEMPORAL',
                                                                  'PLANTA' ) ),
   nombre_cafeteria    varchar2(255) not null,
   porcentaje_comision number not null check ( porcentaje_comision >= 0
      and porcentaje_comision <= 100 ),
   primary key ( id_colaborador ),
   foreign key ( nombre_cafeteria )
      references cafeteria ( nombre )
         on delete set null
);

create table inventariocafeteria (
   nombre_cafeteria varchar2(255) not null,
   nombre_producto  varchar2(255) not null,
   existencias      int not null check ( existencias >= 0 ),
   primary key ( nombre_cafeteria,
                 nombre_producto ),
   foreign key ( nombre_cafeteria )
      references cafeteria ( nombre )
         on delete set null,
   foreign key ( nombre_producto )
      references producto ( nombre_producto )
         on delete set null
);

create table compra (
   id_compra      number
      generated by default on null as identity,
   id_miembro     number not null,
   id_colaborador number not null,
   fecha          date not null,
   total_compra   number check ( total_compra >= 0 ),
   primary key ( id_compra ),
   foreign key ( id_miembro )
      references miembro ( id_miembro )
         on delete set null,
   foreign key ( id_colaborador )
      references colaborador ( id_colaborador )
         on delete set null
);

create table compraxproducto (
   id_compra       number
      generated by default on null as identity,
   nombre_producto varchar2(255),
   cantidad        int not null check ( cantidad > 0 ),
   primary key ( id_compra,
                 nombre_producto ),
   foreign key ( id_compra )
      references compra ( id_compra )
         on delete set null,
   foreign key ( nombre_producto )
      references producto ( nombre_producto )
         on delete set null
);

create table txpuntos (
   id_txpuntos  number
      generated by default on null as identity,
   id_compra    number,
   id_miembro   number not null,
   fecha        date not null,
   total_puntos number not null check ( total_puntos != 0 ),
   tipo         varchar2(10) not null check ( tipo in ( 'CANJE',
                                                'COMPRA',
                                                'ACUMULAR' ) ),
   primary key ( id_txpuntos ),
   foreign key ( id_compra )
      references compra ( id_compra )
         on delete set null,
   foreign key ( id_miembro )
      references miembro ( id_miembro )
         on delete set null
);

create table impuestoxcompra (
   id_impuesto   number
      generated by default on null as identity,
   id_compra     number not null,
   tipo_impuesto varchar2(20) not null check ( tipo_impuesto in ( 'IVA',
                                                                  'ISR',
                                                                  'ICA' ) ),
   porcentaje    number not null check ( porcentaje >= 0
      and porcentaje <= 100 ),
   primary key ( id_impuesto ),
   foreign key ( id_compra )
      references compra ( id_compra )
         on delete set null
);

create table pago (
   id_pago        number
      generated by default on null as identity,
   id_compra      number not null,
   monto_total    number not null check ( monto_total >= 0 ),
   metodo_pago    varchar2(20) not null check ( metodo_pago in ( 'CREDITO',
                                                              'DEBITO',
                                                              'EFECTIVO',
                                                              'PUNTOS' ) ),
   numero_tarjeta varchar2(16),
   primary key ( id_pago ),
   foreign key ( id_compra )
      references compra ( id_compra )
         on delete set null
);