drop table notificaciones_puntos;
drop table log_miembro;
drop table log_inventario;
drop table auditoria_compra;
drop table compraxproducto;
drop table txpuntos;
drop table impuestoxcompra;
drop table miembroxcorreo;
drop table pago;
drop table compra;
drop table inventariocafeteria;
drop table producto;
drop table comisiondiariacolaborador; -- CA-1
drop table colaborador;
drop table cafeteria;
drop table piso;
drop table edificio;
drop table miembro;
drop table puntos;